=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="_ItemName.xsd"/>
    <!--do not put any element before includes-->
    <xs:element name="database" type="databaseType"/>
    <xs:complexType name="PresetItemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="ItemName" name="Name" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
                <xs:attribute type="xs:float" name="Quality" use="optional"/>
                <xs:attribute type="xs:float" name="Condition" use="optional"/>
                <xs:attribute type="xs:float" name="ConditionVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="InventoryPresetType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="PresetItemType" name="PresetItem">
                <xs:annotation>
                </xs:annotation>
            </xs:element>
            <xs:element type="InventoryPresetRefType" name="InventoryPresetRef">
                <xs:annotation>
                </xs:annotation>
            </xs:element>
            <xs:element type="ClothingPresetRefType" name="ClothingPresetRef">
            </xs:element>
            <xs:element type="WeaponPresetRefType" name="WeaponPresetRef">
            </xs:element>
        </xs:choice>
        <xs:attribute type="xs:string" name="Name" use="optional"/>
        <xs:attribute type="xs:string" name="Mode" use="optional"/>
        <xs:attribute type="xs:string" name="ModeValue" use="optional"/>
        <xs:attribute type="xs:string" name="ModeValueVariation" use="optional"/>
        <xs:attribute type="xs:float" name="Health" use="optional"/>
        <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
        <xs:attribute type="xs:int" name="Amount" use="optional"/>
        <xs:attribute type="xs:int" name="AmountCount" use="optional"/>
        <xs:attribute type="xs:int" name="AmountVariation" use="optional"/>
    </xs:complexType>
    <xs:complexType name="InventoryPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ClothingPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="WeaponPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="InventoryPresetsType">
        <xs:sequence>
            <xs:element type="InventoryPresetType" name="InventoryPreset" maxOccurs="unbounded" minOccurs="0">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="version"/>
    </xs:complexType>
    <xs:complexType name="databaseType">
        <xs:sequence>
            <xs:element type="InventoryPresetsType" name="InventoryPresets"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
</xs:schema>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_bratriZCimburka.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_1">
			<WeaponPresetRef Name="axe_shield_4_01_cuman" />
			<ClothingPresetRef Name="cuman_4_01" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_2">
			<WeaponPresetRef Name="axe_shield_4_03_cuman" />
			<ClothingPresetRef Name="cuman_3_01" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_3">
			<WeaponPresetRef Name="archer_4_01_cuman" />
			<ClothingPresetRef Name="cuman_3_02" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_4">
			<WeaponPresetRef Name="huntingsword_shield_4_02_cuman" />
			<ClothingPresetRef Name="cuman_4_02" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_5">
			<WeaponPresetRef Name="sabre_shield_3_01_cuman" />
			<ClothingPresetRef Name="cuman_4_03" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_6">
			<WeaponPresetRef Name="archer_3_01_cuman" />
			<ClothingPresetRef Name="cuman_3_03" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_7">
			<WeaponPresetRef Name="archer_4_01_cuman" />
			<ClothingPresetRef Name="cuman_4_01" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_cuman_8">
			<WeaponPresetRef Name="archer_4_01_cuman" />
			<ClothingPresetRef Name="cuman_4_04" />
			<InventoryPresetRef Name="pockets_bandit_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_dead_priest">
			<ClothingPresetRef Name="bratriZCimburka_deadPriest" />
			<InventoryPresetRef Name="inventory_empty" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_pillager_1">
			<InventoryPresetRef Name="melee_combat_level_2_axe" />
			<ClothingPresetRef Name="bratriZCimburka_vagabond_01" />
			<InventoryPresetRef Name="pockets_bandit_light" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_pillager_2">
			<InventoryPresetRef Name="melee_combat_level_1_huntingsword" />
			<ClothingPresetRef Name="bratriZCimburka_vagabond_02" />
			<InventoryPresetRef Name="pockets_bandit_light" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_pillager_3">
			<InventoryPresetRef Name="missile_combat_level_2_bow" />
			<ClothingPresetRef Name="bratriZCimburka_vagabond_03" />
			<InventoryPresetRef Name="pockets_bandit_light" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_bratriZCimburka_pillager_4">
			<WeaponPresetRef Name="bratriZCimburka_mace_shield_looted" />
			<ClothingPresetRef Name="bratriZCimburka_vagabond_04" />
			<InventoryPresetRef Name="pockets_bandit_light" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_cimburk_soldier" Mode="OneChild">
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_04" />
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_02" />
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_03" />
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_01" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_cimburk_soldier_1">
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_04" />
			<InventoryPresetRef Name="inventory_empty" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_cimburk_soldier_2">
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_02" />
			<InventoryPresetRef Name="inventory_empty" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_cimburk_soldier_3">
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_03" />
			<InventoryPresetRef Name="inventory_empty" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_cimburk_soldier_4">
			<ClothingPresetRef Name="bratriZCimburka_deadSoldier_01" />
			<InventoryPresetRef Name="inventory_empty" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kbyl_jan">
			<WeaponPresetRef Name="kbyl_jan" />
			<ClothingPresetRef Name="kbyl_jan" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kvrc_fiolka">
			<ClothingPresetRef Name="f_kvrc_fiolka" />
			<PresetItem Name="herb_chamomile" Amount="4" />
			<PresetItem Name="herb_wormwood" Amount="2" />
			<InventoryPresetRef Name="pockets_villager" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kvrc_miroslav">
			<ClothingPresetRef Name="bratriZCimburka_miroslavInJail" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kbyl_janHorse">
			<ClothingPresetRef Name="kbyl_janHorse" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kbyl_miroslavHorse">
			<ClothingPresetRef Name="kbyl_miroslavHorse" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_drak.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="drak_alchemist">
			<ClothingPresetRef Name="drak_alchemist_S30" />
			<InventoryPresetRef Name="weapons_shortsword_combatLevel_all" />
			<InventoryPresetRef Name="inventory_money_fewBeers" />
			<PresetItem Name="bandage_classic" Amount="2"/>
			<PresetItem Name="potion_aquaVitalis_high" Amount="2" />
			<PresetItem Name="potion_embrocation_high" Amount="1" />
			<PresetItem Name="potion_painkiller_high" Amount="2" />
			<PresetItem Name="potion_saviourSchnapps_high" Amount="1" />
			<PresetItem Name="potion_nighthawk" Amount="1" />
			<PresetItem Name="special_bezoar" Amount="1" />
			<PresetItem Name="special_mushroomAmanita" Amount="8" />
			<PresetItem Name="loot_oakGallInk" Amount="3" />
			<PresetItem Name="herb_dried_hypericum" Amount="17" />
			<PresetItem Name="herb_dried_belladona" Amount="21" />
			<PresetItem Name="herb_dried_paris" Amount="11" />
			<PresetItem Name="skillbook_alchemy_IV_kcd2" Amount="1" />
			<PresetItem Name="recipe_paralysisPotion" Amount="1" />
			<PresetItem Name="recipe_energyPotion" Amount="1" />
			<PresetItem Name="daggerCommon" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_drak_gerhart_horse">
			<ClothingPresetRef Name="horse_common02" />
		</InventoryPreset>
		<InventoryPreset Name="drak_alchemistBodyguard1">
			<ClothingPresetRef Name="drak_alchemistBodyguard1_S30" />
			<InventoryPresetRef Name="weapons_shortsword_combatLevel_all" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="drak_alchemistBodyguard2">
			<ClothingPresetRef Name="drak_alchemistBodyguard2_S30" />
			<InventoryPresetRef Name="weapons_shortsword_combatLevel_all" />
			<InventoryPresetRef Name="pockets_soldiers_all" />   
		</InventoryPreset>
		<InventoryPreset Name="drak_alchemistBodyguard3">
			<ClothingPresetRef Name="drak_alchemistBodyguard3_S30" />
			<InventoryPresetRef Name="weapons_oneHand_combatLevel_all" />
			<InventoryPresetRef Name="pockets_soldiers_all" />   
		</InventoryPreset>
		<InventoryPreset Name="drak_zikmund_soldier1">
			<ClothingPresetRef Name="drak_zikmund_soldier1_S30" />
			<InventoryPresetRef Name="melee_combat_level_3_sword_shield_sigi" />
			<InventoryPresetRef Name="pockets_soldiers_all" />  
		</InventoryPreset>
		<InventoryPreset Name="drak_zikmund_soldier2">
			<ClothingPresetRef Name="drak_zikmund_soldier2_S30" />
			<InventoryPresetRef Name="melee_combat_level_3_sword_shield_sigi" />
			<InventoryPresetRef Name="pockets_soldiers_all" />  
		</InventoryPreset>
		<InventoryPreset Name="drak_zikmund_soldier3">
			<ClothingPresetRef Name="drak_zikmund_soldier3_S30" />
			<InventoryPresetRef Name="crossbowman_combatLevel_all" />
			<InventoryPresetRef Name="pockets_soldiers_all" />   
		</InventoryPreset>
		<InventoryPreset Name="drak_zikmund_soldierLeader">
			<ClothingPresetRef Name="drak_zikmund_soldierLeader_S30" />
			<InventoryPresetRef Name="weapons_longsword_combatLevel_all" />
			<InventoryPresetRef Name="pockets_soldiers_all" />   
		</InventoryPreset>
		<InventoryPreset Name="inventory_drak_gerhart">
			<ClothingPresetRef Name="drak_gerhart_s30" />
			<InventoryPresetRef Name="weapons_noble_combatLevel_all" />
			<InventoryPresetRef Name="pockets_burgher" />   
		</InventoryPreset>
		<InventoryPreset Name="inventory_drak_horse">
			<ClothingPresetRef Name="drak_AlchemistHorse_s30" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_fistfightsHorany.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_fistfightsHorany_beruska">
			<ClothingPresetRef Name="fighterCivil_11_Beruska" />
			<InventoryPresetRef Name="pockets_villager"/>
			<InventoryPresetRef Name="pockets_fighter" />
			<InventoryPresetRef Name="inventory_money_pairOfShoes" />
			<PresetItem Name="herb_dandelion" Amount="3" />
			<PresetItem Name="BasicBridle02_m01" Amount="1" />
			<PresetItem Name="lambMeat" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_fistfightsHorany_stanik">
			<ClothingPresetRef Name="fighterCivil_13_Stanik" />
			<InventoryPresetRef Name="pockets_villager"/>
			<InventoryPresetRef Name="pockets_fighter" />
			<InventoryPresetRef Name="inventory_money_pairOfShoes" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_fistfightsHorany_tuma">
			<ClothingPresetRef Name="fighterCivil_12_Tuma" />
			<InventoryPresetRef Name="pockets_villager"/>
			<InventoryPresetRef Name="pockets_fighter" />
			<InventoryPresetRef Name="inventory_money_pairOfShoes" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__event_rvacka.xml
<?xml version='1.0' encoding='us-ascii'?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">

		<InventoryPreset Name="inventory_rvacka_cuman" Mode="All" Health="0.39" HealthVariation="0.05">
			<InventoryPresetRef Name="inventory_rvacka_cuman_clothes"/>
			<InventoryPresetRef Name="pockets_bandit_all"/>
		</InventoryPreset>   

		<InventoryPreset Name="inventory_rvacka_cuman_clothes" Mode="OneChild">
			<ClothingPresetRef Name="rvacka_sigiCamp_01"/>
			<ClothingPresetRef Name="rvacka_sigiCamp_02"/>
			<ClothingPresetRef Name="rvacka_sigiCamp_03"/>
			<ClothingPresetRef Name="rvacka_sigiCamp_04"/>
		</InventoryPreset>

		<InventoryPreset Name="inventory_rvacka_bouncer_1">
			<ClothingPresetRef Name="rvacka_bouncer_1"/>
		</InventoryPreset>

		<InventoryPreset Name="inventory_rvacka_bouncer_2">
			<ClothingPresetRef Name="rvacka_bouncer_2"/>
		</InventoryPreset>

		<InventoryPreset Name="inventory_rvacka_drunkard">
			<ClothingPresetRef Name="rvacka_drunkard"/>
		</InventoryPreset>		

	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_havirskyTurnaj.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_havirskyTurnaj_animchars" >
			<InventoryPresetRef Name="inventory_havirskyTurnaj_festiveWeapons" />
			<InventoryPresetRef Name="inventory_havirskyTurnaj_festiveClothing" />
			<InventoryPresetRef Name="pockets_miner" />
		</InventoryPreset>
		<!--=====PRESETS FOR MINERS===================================-->
		<InventoryPreset Name="inventory_havirskyTurnaj_festiveClothing" Mode="OneChild">
			<ClothingPresetRef Name="miner_01" Weight="0.7" />
			<ClothingPresetRef Name="miner_02" Weight="0.6" />
			<ClothingPresetRef Name="miner_03" Weight="0.7" />
			<ClothingPresetRef Name="miner_04" Weight="0.6" />
			<ClothingPresetRef Name="miner_05" Weight="0.7" />
			<ClothingPresetRef Name="miner_06" Weight="0.8" />
			<ClothingPresetRef Name="miner_07" Weight="0.7" />
			<ClothingPresetRef Name="miner_08" Weight="0.6" />
			<ClothingPresetRef Name="miner_09" Weight="0.8" />
			<ClothingPresetRef Name="miner_10" Weight="0.7" />
			<ClothingPresetRef Name="miner_11" Weight="0.6" />
			<ClothingPresetRef Name="miner_12" Weight="0.7" />
			<ClothingPresetRef Name="miner_13" Weight="0.6" />
			<ClothingPresetRef Name="miner_festive_01" Weight="1.5" />
			<ClothingPresetRef Name="miner_festive_02" Weight="1" />
			<ClothingPresetRef Name="miner_festive_03" Weight="1.1" />
			<ClothingPresetRef Name="miner_festive_04" Weight="1" />
			<ClothingPresetRef Name="miner_festive_05" Weight="1.1" />
			<ClothingPresetRef Name="miner_festive_06" Weight="1" />
			<ClothingPresetRef Name="miner_festive_07" Weight="0.8" />
			<ClothingPresetRef Name="miner_festive_08" Weight="0.8" />
			<ClothingPresetRef Name="miner_festive_09" Weight="1" />
			<ClothingPresetRef Name="miner_festive_10" Weight="1" />

		</InventoryPreset>
		<InventoryPreset Name="inventory_havirskyTurnaj_festiveWeapons" Mode="OneChild">
			<WeaponPresetRef Name="miner_festiveWeapon_01" Weight="0.8" />
			<WeaponPresetRef Name="miner_festiveWeapon_02" Weight="0.9" />
			<WeaponPresetRef Name="miner_festiveWeapon_03" Weight="1.1" />
			<WeaponPresetRef Name="miner_festiveWeapon_04" Weight="1" />
			<WeaponPresetRef Name="miner_festiveWeapon_05" Weight="0.4" />
			<WeaponPresetRef Name="miner_festiveWeapon_06" Weight="1.1" />
			<WeaponPresetRef Name="miner_festiveWeapon_07" Weight="1" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_andelStrazny.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_andelStraznyRiddle1">
            <PresetItem Name="andelStrazny_riddles_2"/>
        </InventoryPreset>
        <InventoryPreset Name="inventory_andelStraznyRiddle2">
            <PresetItem Name="andelStrazny_riddles_3"/>
        </InventoryPreset>
        <InventoryPreset Name="inventory_andelStraznyRiddle3">
            <PresetItem Name="andelStrazny_riddles_4"/>
        </InventoryPreset>
        <InventoryPreset Name="inventory_andelStraznyRiddle4">
            <PresetItem Name="andelStrazny_riddles_5"/>
        </InventoryPreset>
        <InventoryPreset Name="inventory_andelStraznyRiddle5">
            <PresetItem Name="skillbook_alchemy_IV_kcd2"/>
            <PresetItem Name="skillbook_scholarship_IV_KCD2"/>
        </InventoryPreset>
	</InventoryPresets>
</database>
