=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="_ItemName.xsd"/>
    <!--do not put any element before includes-->
    <xs:element name="database" type="databaseType"/>
    <xs:complexType name="PresetItemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="ItemName" name="Name" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
                <xs:attribute type="xs:float" name="Quality" use="optional"/>
                <xs:attribute type="xs:float" name="Condition" use="optional"/>
                <xs:attribute type="xs:float" name="ConditionVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="InventoryPresetType" mixed="true">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element type="PresetItemType" name="PresetItem">
                <xs:annotation>
                </xs:annotation>
            </xs:element>
            <xs:element type="InventoryPresetRefType" name="InventoryPresetRef">
                <xs:annotation>
                </xs:annotation>
            </xs:element>
            <xs:element type="ClothingPresetRefType" name="ClothingPresetRef">
            </xs:element>
            <xs:element type="WeaponPresetRefType" name="WeaponPresetRef">
            </xs:element>
        </xs:choice>
        <xs:attribute type="xs:string" name="Name" use="optional"/>
        <xs:attribute type="xs:string" name="Mode" use="optional"/>
        <xs:attribute type="xs:string" name="ModeValue" use="optional"/>
        <xs:attribute type="xs:string" name="ModeValueVariation" use="optional"/>
        <xs:attribute type="xs:float" name="Health" use="optional"/>
        <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
        <xs:attribute type="xs:int" name="Amount" use="optional"/>
        <xs:attribute type="xs:int" name="AmountCount" use="optional"/>
        <xs:attribute type="xs:int" name="AmountVariation" use="optional"/>
    </xs:complexType>
    <xs:complexType name="InventoryPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ClothingPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="WeaponPresetRefType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="Name" use="optional"/>
                <xs:attribute type="xs:float" name="Weight" use="optional"/>
                <xs:attribute type="xs:float" name="CombatLevel" use="optional"/>
                <xs:attribute type="xs:int" name="Amount" use="optional"/>
                <xs:attribute type="xs:string" name="ItemClassId" use="optional"/>
                <xs:attribute type="xs:float" name="Health" use="optional"/>
                <xs:attribute type="xs:float" name="HealthVariation" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="InventoryPresetsType">
        <xs:sequence>
            <xs:element type="InventoryPresetType" name="InventoryPreset" maxOccurs="unbounded" minOccurs="0">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:string" name="version"/>
    </xs:complexType>
    <xs:complexType name="databaseType">
        <xs:sequence>
            <xs:element type="InventoryPresetsType" name="InventoryPresets"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
</xs:schema>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_svatyAntonin.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_kkut_druhySvaty">
			<ClothingPresetRef Name="kkut_druhySvaty" />
			<WeaponPresetRef Name="mace_2_03" />
			<InventoryPresetRef Name="pockets_gambler" />
			<InventoryPresetRef Name="inventory_singleRandomAlcohol" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
			<PresetItem Name="potion_artemisia_high" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kkut_hospodskySvatych">
			<ClothingPresetRef Name="kkut_hospodskySvatych" />
			<InventoryPresetRef Name="pockets_innkeeper" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
			<PresetItem Name="svatyAntonin_tavernSvatychCellarDoor" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kkut_jorgPrank">
			<ClothingPresetRef Name="kkut_jorgPrank" />
			<WeaponPresetRef Name="hammer_3_01" />
			<InventoryPresetRef Name="pockets_burgher" />
			<PresetItem Name="svatyAntonin_tavernSvatychCellarDoor" Amount="1" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
			<PresetItem Name="arrow_precise" Amount="12" />
			<PresetItem Name="repairKit_bowyerSmall" Amount="1" />
			<PresetItem Name="potion_painkiller" Amount="1" />
			<PresetItem Name="RerollDiceBadgeSilver" Amount="1" />
			<PresetItem Name="die_Gamblerova_good" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_kkut_prvniSvaty">
			<ClothingPresetRef Name="kkut_prvniSvaty" />
			<WeaponPresetRef Name="hammer_2_01" />
			<InventoryPresetRef Name="pockets_gambler" />
			<InventoryPresetRef Name="inventory_singleRandomAlcohol" />
			<PresetItem Name="player_lockpick" Amount="2" />
			<PresetItem Name="bandage_classic" Amount="1" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_bannerChest">
			<InventoryPresetRef Name="inventory_banditLoot_smallAmountOfValuables" />
			<InventoryPresetRef Name="inventory_banditLoot_spareWeapons" />
			<PresetItem Name="wineGood" Amount="2" />
			<PresetItem Name="potion_artemisia_medium" Amount="2" />
			<PresetItem Name="loot_goldenChalice" Amount="1" />
			<PresetItem Name="loot_silverCup" Amount="2" />
			<PresetItem Name="money" Amount="3120" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_gamblers">
			<InventoryPresetRef Name="pockets_gambler" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_gamblers_dedicatedGambler">
			<InventoryPresetRef Name="clothes_burgher_male" />
			<InventoryPresetRef Name="pockets_villager" />
			<PresetItem Name="svatyAntonin_saintGameSign" Amount="1" />
			<PresetItem Name="ExtraDicebadgeSilver" Amount="1" />
			<PresetItem Name="AntibustDiceBadgePlumb" Amount="1" />
			<PresetItem Name="die_Matematikova" Amount="1" />
			<PresetItem Name="money" Amount="3800" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_hensl">
			<PresetItem Name="TunicLong01_m04_C" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_lazar">
			<ClothingPresetRef Name="kkut_lazar" />
			<InventoryPresetRef Name="pockets_miner" />
			<InventoryPresetRef Name="inventory_singleRandomAlcohol" />
			<PresetItem Name="bolt_enh_precise" Amount="8" />
			<PresetItem Name="repairKit_bowyerSmall" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_francek">
			<ClothingPresetRef Name="kkut_francek" />
			<WeaponPresetRef Name="mace_1_01" />
			<InventoryPresetRef Name="pockets_miner" />
			<InventoryPresetRef Name="inventory_singleRandomAlcohol" />
			<PresetItem Name="repairKit_cobblersSmall" Amount="1" />
			<PresetItem Name="bandage_classic" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_svatyAntonin_anton">
			<ClothingPresetRef Name="kkut_anton" />
			<WeaponPresetRef Name="mace_2_03" />
			<InventoryPresetRef Name="pockets_burgher" />
			<PresetItem Name="bolt_enh_precise" Amount="12" />
			<PresetItem Name="potion_stamina" Amount="1" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__tvez.xml
<?xml version='1.0' encoding='us-ascii'?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_fishermansStash">
			<PresetItem Name="wineGood" Amount="1"/>
			<PresetItem Name="poi_earthworm" Amount="58"/>
			<PresetItem Name="bread" Amount="2"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_poachersSack">
			<PresetItem Name="money" Amount="380"/>
			<PresetItem Name="skin_wolf" Amount="2"/>
			<PresetItem Name="skin_roe" Amount="7"/>
			<PresetItem Name="skin_boar" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_bozena">
			<ClothingPresetRef Name="f_tvez_bozena"/>
			<InventoryPresetRef Name="pockets_herbalist"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_concubine">
			<ClothingPresetRef Name="tvez_concubine"/>
			<InventoryPresetRef Name="pockets_herbalist"/>
			<PresetItem Name="herb_dried_mint" Amount="3"/>
			<PresetItem Name="lorebook_onMaidensWar" Amount="1"/>
			<PresetItem Name="paralysisPoison" Amount="1"/>
			<PresetItem Name="soap" Amount="1"/>
			<PresetItem Name="repairKit_tailorsSmall" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_aranka">
			<ClothingPresetRef Name="tvez_aranka"/>
			<PresetItem Name="herb_thistle" Amount="2"/>
			<PresetItem Name="herb_salvia" Amount="1"/>
			<PresetItem Name="herb_marigold" Amount="2"/>
			<InventoryPresetRef Name="pockets_villager"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_divozenka">
			<ClothingPresetRef Name="tvez_divozenka"/>
			<InventoryPresetRef Name="pockets_herbalist"/>
			<PresetItem Name="perchDried" Amount="2"/>
			<PresetItem Name="herb_chamomile" Amount="28"/>
			<PresetItem Name="herb_dandelion" Amount="14"/>
			<PresetItem Name="herb_comfrey" Amount="5"/>
			<InventoryPresetRef Name="inventory_money_onePig"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_kocour" Health="0.06" HealthVariation="0.05">
			<ClothingPresetRef Name="tvez_kocour_battle"/>
			<WeaponPresetRef Name="longsword_5_01_torch"/>
			<InventoryPresetRef Name="pockets_gambler"/>
			<PresetItem Name="player_lockpick" Amount="2"/>
			<PresetItem Name="bandage_classic" Amount="1"/>
			<PresetItem Name="repairKit_cobblersSmall" Amount="1"/>
			<PresetItem Name="potion_stamina" Amount="1" Health="1"/>
			<PresetItem Name="potion_painkiller_high" Amount="1" Health="1"/>
			<PresetItem Name="daggerCommon" Amount="1"/>
			<InventoryPresetRef Name="inventory_pileOfOnion"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_marika">
			<ClothingPresetRef Name="tvez_marika"/>
			<InventoryPresetRef Name="inventory_singleRandomPoorSnack"/>
			<PresetItem Name="herb_valerian" Amount="1"/>
			<PresetItem Name="herb_paris" Amount="1"/>
			<PresetItem Name="herb_wormwood" Amount="1"/>
			<InventoryPresetRef Name="inventory_money_lostChange"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_pavlena">
			<ClothingPresetRef Name="f_tvez_pavlena"/>
			<InventoryPresetRef Name="pockets_herbalist"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_tibor">
			<ClothingPresetRef Name="tvez_tibor"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_vasko" Health="0.06" HealthVariation="0.05"> <!--kumansky velitel Vasko-->
			<ClothingPresetRef Name="tvez_vasko"/>
			<WeaponPresetRef Name="tvez_vasko"/>
			<InventoryPresetRef Name="pockets_bandit_heavy"/>
			<InventoryPresetRef Name="inventory_chanceOfSingleBurgherValuable"/>
			<InventoryPresetRef Name="light_torch"/>
			<PresetItem Name="apple" Amount="1" Health="1" HealthVariation="0.3"/>
			<PresetItem Name="repairKit_weaponSmall" Amount="1"/>
			<PresetItem Name="repairKit_bowyerSmall" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_vajda" Health="0.12" HealthVariation="0.05">
			<ClothingPresetRef Name="tvez_vajda"/>
			<WeaponPresetRef Name="tvez_vajda"/>
			<InventoryPresetRef Name="pockets_burgher"/>
			<PresetItem Name="ring_silver_gem" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_kocovnickaCest_gejza">
			<ClothingPresetRef Name="kocovnickaCest_gejza"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_utopenciStash">
			<PresetItem Name="money" Amount="1380"/>
			<PresetItem Name="poi_vodnik_treasureMap" Amount="1"/>
			<PresetItem Name="wineGood" Amount="1"/>
			<PresetItem Name="duck" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_vodnikShelf">
			<PresetItem Name="money" Amount="50"/>
			<PresetItem Name="crayfish" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_vodnikStash">
			<PresetItem Name="money" Amount="130"/>
			<PresetItem Name="poi_vodnik_vodnikovyKalhoty" Amount="1"/>
			<PresetItem Name="perch" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_vodniksTreasure">
			<PresetItem Name="money" Amount="1250"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_certuvPrstStash">
			<PresetItem Name="money" Amount="2810"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_jugAtRuinedHouse">
			<PresetItem Name="money" Amount="300"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_sackUnderTheLog">
			<PresetItem Name="money" Amount="250"/>
			<PresetItem Name="beefDried" Amount="6" Health="0.81"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_8"> <!--kumansky pobocnik Jasak-->
			<ClothingPresetRef Name="tvez_man_8"/>
			<WeaponPresetRef Name="tvez_man_8"/>
			<InventoryPresetRef Name="pockets_bandit_medium"/>
			<InventoryPresetRef Name="inventory_chanceOfSingleBurgherValuable"/>
			<PresetItem Name="apple" Amount="1" Health="1" HealthVariation="0.3"/>
			<PresetItem Name="repairKit_weaponSmall" Amount="1"/>
			<PresetItem Name="repairKit_bowyerSmall" Amount="1"/>
			<!-- netreba kapes -->
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_9"> 
			<ClothingPresetRef Name="tvez_man_9"/>
			<WeaponPresetRef Name="tvez_man_9"/>
			<InventoryPresetRef Name="pockets_bandit_medium"/>
			<InventoryPresetRef Name="inventory_chanceOfSingleBurgherValuable"/>
			<PresetItem Name="pear" Amount="1" Health="1" HealthVariation="0.3"/>
			<PresetItem Name="repairKit_bowyerSmall" Amount="1"/>
			<PresetItem Name="repairKit_armourSmall" Amount="2"/>
			<!-- netreba kapes -->
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_11"> 
			<ClothingPresetRef Name="tvez_man_11"/>
			<WeaponPresetRef Name="tvez_man_11"/>
			<InventoryPresetRef Name="pockets_bandit_medium"/>
			<PresetItem Name="walnuts" Amount="1" Health="1" HealthVariation="0.3"/>
			<PresetItem Name="repairKit_armourSmall" Amount="1"/>
			<PresetItem Name="repairKit_cobblersSmall" Amount="1"/>
			<!-- netreba kapes -->
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_12"> 
			<ClothingPresetRef Name="tvez_man_12"/>
			<WeaponPresetRef Name="tvez_man_12"/>
			<InventoryPresetRef Name="pockets_bandit_light"/>
			<PresetItem Name="repairKit_bowyerSmall" Amount="1"/>
			<PresetItem Name="repairKit_weaponSmall" Amount="1"/>
			<InventoryPresetRef Name="inventory_money_pairOfShoes" />
			<InventoryPresetRef Name="inventory_chanceOfSingleBurgherValuable" />
			<!-- netreba kapes -->
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_5">
			<ClothingPresetRef Name="tvez_man_5"/>
			<InventoryPresetRef Name="pockets_huntsman"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_woman_2">
			<ClothingPresetRef Name="tvez_woman_2"/>
			<!-- <InventoryPresetRef Name="pockets_bathmaid"/> -->
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_woman_1">
			<ClothingPresetRef Name="tvez_woman_1"/>
			<InventoryPresetRef Name="pockets_villager"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_mikolaj">
			<ClothingPresetRef Name="tvez_mikolaj"/>
			<InventoryPresetRef Name="pockets_horseTrader"/>
			<PresetItem Name="hadkaKonaru_crossCountryChestKey" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_bibrek">
			<ClothingPresetRef Name="tvez_bibrek"/>
			<PresetItem Name="hadkaKonaru_mountedArcheryChestKey" Amount="1"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_2">
			<ClothingPresetRef Name="tvez_man_2"/>
			<InventoryPresetRef Name="pockets_villager"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_4">
			<ClothingPresetRef Name="tvez_man_4"/>
			<InventoryPresetRef Name="weapons_combatLevel_tro"/>
			<InventoryPresetRef Name="pockets_soldiers_all"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_man_3">
			<ClothingPresetRef Name="tvez_man_3"/>
			<InventoryPresetRef Name="weapons_combatLevel_tro"/>
			<InventoryPresetRef Name="pockets_soldiers_all"/>
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_opilecAVandrak_man_1">
			<InventoryPresetRef Name="clothes_beggar_male"/> 
			<InventoryPresetRef Name="pockets_beggar"/> 
			<InventoryPresetRef Name="weapons_rabble_combatLevel_all"/> 
		</InventoryPreset>
		<InventoryPreset Name="inventory_tvez_wolfDenStash">
			<PresetItem Name="ring_silver_gem" Amount="1" />
			<PresetItem Name="necklace_tin_cross" Amount="1" />
			<PresetItem Name="Spectacles01_m01" Amount="1" />
			<PresetItem Name="money" Amount="40" />
			<PresetItem Name="rabbitMeat" Amount="2" Health="0.48"/>
			<PresetItem Name="lambMeat" Amount="1" Health="0.43"/>
		</InventoryPreset>

	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_ztracenaCest.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_ztracenaCest_gringolet">
			<ClothingPresetRef Name="kzik_horse_gringolet" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_ztracenaCest_jezek">
			<ClothingPresetRef Name="ztracenaCest_jezek" />
			<WeaponPresetRef Name="ztracenaCest_Jezek" />
			<PresetItem Name="money" Amount="5000" />
			<!-- <PresetItem Name="Spurs01_m01_C" Amount="1" /> Spurs are assigned in Skald -->
			<!-- <PresetItem Name="ztracenaCest_lordsOfHolohlavShield" Amount="1" />  --> <!-- The shield is inside weapon preset -->
			<InventoryPresetRef Name="pockets_villager" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_ztracenaCest_zavis">
			<ClothingPresetRef Name="kzik_zavis" />
			<InventoryPresetRef Name="weapons_longsword_combatLevel_all" />
			<PresetItem Name="ztracenaCest_zavisChest" Amount="1" />
			<InventoryPresetRef Name="pockets_villager" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__ksus.xml
<?xml version='1.0' encoding='us-ascii'?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">

		<InventoryPreset Name="inventory_ksus_secreMint" Health="0.24" HealthVariation="0.05">
			<PresetItem Name="HoseSeparate01_m09_D" Amount="1"/>
			<PresetItem Name="Hood07_m02_C" Amount="1"/>
			<PresetItem Name="TunicShort08_m09_C" Amount="1" Quality="3" Condition="0.2"/>
			<PresetItem Name="special_sulfur" Amount="6"/>
			<PresetItem Name="potion_nighthawk_medium" Amount="2" Health="1"/>
			<PresetItem Name="special_saltpeter" Amount="8"/>
		</InventoryPreset>

	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_finale.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
	<InventoryPresets version="2">
		<InventoryPreset Name="inventory_finale_axeman">
			<WeaponPresetRef Name="axe_2_01" />
			<InventoryPresetRef Name="praguers_uniform_heavy" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_finale_boss">
			<WeaponPresetRef Name="longsword_6_01" />
			<InventoryPresetRef Name="clothes_genericSoldier_combatLevel_kut" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_finale_hanus_army">
			<InventoryPresetRef Name="melee_combat_level_5_sword_shield_lipa" /> <!-- Souls have CS mocaped animations with shortswords -->
			<InventoryPresetRef Name="leipa_army_uniform" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_finale_wallGuy">
			<WeaponPresetRef Name="polearm_5_01" />
			<InventoryPresetRef Name="praguers_uniform_heavy" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_lamprecht_von_prag">
			<WeaponPresetRef Name="longsword_6_01" />
			<ClothingPresetRef Name="finale_lamprecht_von_prag" />
			<InventoryPresetRef Name="pockets_noble" />
		</InventoryPreset>
		<InventoryPreset Name="leipa_army_uniform" Mode="OneChild">
			<ClothingPresetRef Name="soldier_lipa_4_02" />
			<ClothingPresetRef Name="soldier_lipa_4_01" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_finale_limmy" >
			<PresetItem Name="loot_gooseFeathers" Amount="10" />
			<PresetItem Name="bsmt_steelGood" Amount="1" />
		</InventoryPreset>
		<InventoryPreset Name="inventory_finale_healedSoldier" >
			<ClothingPresetRef Name="finale_jostSoldier_02_noHeadwear" />
		</InventoryPreset>
	</InventoryPresets>
</database>

=== bikeracer4487/kcd2_gear_picker/kcd2-ref/Libs/Tables/item/InventoryPreset__quests_stealthMiseZaJindru.xml
<?xml version="1.0" encoding="us-ascii"?>
<database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="barbora" xsi:noNamespaceSchemaLocation="InventoryPreset.xsd">
		<InventoryPresets version="2">
			<InventoryPreset Name="inventory_stealthMiseZaJindru_waffenrockStash">
				<PresetItem Name="Coat04_mPrague_C" Amount="1" />
				<PresetItem Name="Waffenrock01_mPrague01_C" Amount="1" />
				<PresetItem Name="Waffenrock03_mPrague_A" Amount="1" />
				<PresetItem Name="Waffenrock08_mPrague_B" Amount="1" />
			</InventoryPreset>
		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_keyHolder">
		<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_keymaster" />
		<InventoryPresetRef Name="weapons_longsword_combatLevel_all"/>
		<InventoryPresetRef Name="pockets_soldiers_all" />
		<PresetItem Name="stealthMiseZaJindru_aulitzHouseKey" Amount="1" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_general">
			<InventoryPresetRef Name="stealthMiseZaJindru_aulitzsSoldier_generalArmor" />
			<InventoryPresetRef Name="weapons_combatLevel_all_prague" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_outside">
			<InventoryPresetRef Name="stealthMiseZaJindru_aulitzsSoldier_OutsideArmor" />
			<InventoryPresetRef Name="weapons_combatLevel_all_prague" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_honorGuard">
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsGuardOfHonor" />
			<InventoryPresetRef Name="weapons_combatLevel_all_prague" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_drunk1">
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierDrunk_01" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>

		<InventoryPreset Name="inventory_stealthMiseZaJindru_aulitzsSoldier_drunk2">
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierDrunk_02" />
			<InventoryPresetRef Name="pockets_soldiers_all" />
		</InventoryPreset>

	<!-- =================QUEST PRESETY=========== -->

		<InventoryPreset Name="stealthMiseZaJindru_aulitzsSoldier_generalArmor" Mode="OneChild" >
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_01" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_02" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_03" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_04" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_05" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_06" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_07" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_08" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_09" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierInside_10" />
		</InventoryPreset>
		<InventoryPreset Name="stealthMiseZaJindru_aulitzsSoldier_OutsideArmor" Mode="OneChild" >
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_01" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_02" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_03" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_04" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_05" />
			<ClothingPresetRef Name="stealthMiseZaJindru_aulitzsSoldierOutside_06" />
		</InventoryPreset>

	<!-- ====================STASHE=============== -->

	<InventoryPreset Name="stealthMiseZaJindru_aulitzCheberlain_chest" Health="1" HealthVariation="0.1">
		<PresetItem Name="money" Amount="2100" />
		<PresetItem Name="loot_silverCup" Amount="2" />
		<PresetItem Name="loot_copperPlate" Amount="2" />
		<PresetItem Name="wineGood" Amount="4" />
		<PresetItem Name="potion_marigold" Amount="1" />
		<InventoryPresetRef Name="inventory_smallAmountOfSmokedFood" />
	</InventoryPreset>
	<InventoryPreset Name="stealthMiseZaJindru_aulitz_chestRoyal" Health="1" HealthVariation="0.1">
		<PresetItem Name="wineGood" Amount="3" />
		<PresetItem Name="loot_silverCup" Amount="1" />
		<PresetItem Name="Coat01_m09_A" Amount="1" />
		<PresetItem Name="Hood03_m10_A" Amount="1" />
		<PresetItem Name="Cap18_m06_A" Amount="1" />
		<PresetItem Name="HoseJoined02_m08_B" Amount="1" />
		<PresetItem Name="Shoes02_m05_B" Amount="1" />
	</InventoryPreset>
	<InventoryPreset Name="stealthMiseZaJindru_aulitz_chestMetal" Health="1" HealthVariation="0.1">
		<PresetItem Name="ArmPlate04_m03_A5" Amount="1" />
		<PresetItem Name="BascinetVisor04_m03_A5" Amount="2" />
		<PresetItem Name="Cuirass07_m05_A4" Amount="1" />
		<PresetItem Name="LegsBrigandine04_m01_A5" Amount="1" />
		<PresetItem Name="Gauntlets05_m02_A5" Amount="1" />
		<PresetItem Name="GambesonLong03_m11_B4" Amount="1" />
		<PresetItem Name="LegsPadded03_m01_B2" Amount="1" />
		<PresetItem Name="zikmunduv_dopis" Amount="1" />
	</InventoryPreset>
	<InventoryPreset Name="stealthMiseZaJindru_aulitz_chestTreasury" Health="1" HealthVariation="0.1">
		<PresetItem Name="money" Amount="5200" />
		<PresetItem Name="ring_golden_cross" Amount="1" />
		<PresetItem Name="ring_golden_large" Amount="1" />
		<PresetItem Name="ring_engraved_gem" Amount="1" />
		<PresetItem Name="necklace_silver_cross_insignia" Amount="1" />
		<PresetItem Name="necklace_golden_cross_garnet" Amount="1" />
		<PresetItem Name="necklace_scapular_saint" Amount="1" />
		<PresetItem Name="lorebook_queensCourtManuscript" Amount="1" />
	</InventoryPreset>
	<InventoryPreset Name="stealthMiseZaJindru_brabant_chest" Health="1" HealthVariation="0.1">
		<PresetItem Name="money" Amount="3200" />
		<PresetItem Name="ring_silver_gem" Amount="1" />
		<PresetItem Name="ring_silver_engraved" Amount="1" />
		<PresetItem Name="necklace_golden_cross_pearl" Amount="1" />
		<PresetItem Name="loot_silverCup" Amount="1" />
		<PresetItem Name="lorebook_canzoniere" Amount="1" />
	</InventoryPreset>
</InventoryPresets>
</database>
